### ISSUE TITLE
Making the reinforment learning work on a custom net file

### ISSUE THREAD

**Issue by btopii32** [LucasAlegre/sumo-rl#109]
I have cloned the sumo-rl repository. I've seen a lot of files and folders in here. Please I already have my network files, Route file and sumocfg file. How do I start to incorporate reinforment learning in it.
I've been going through the files and I don't know which ones I'll need to use in my traci code. I opened the ql_single-intersection.py and it did run. Am I supposed to use that file and put paths to my custom files there? Thank you

**Comment by LucasAlegre** [comment]
Hi,

Please check the parameters you should pass to the env here: https://github.com/LucasAlegre/sumo-rl/blob/master/sumo_rl/environment/env.py

SUMO-RL only provides the gym or pettingzoo environment. The RL algorithm you can use one of the RL libraries out there. The ql_single_intersection.py is an example using tabular Q-learning (notice that it only works for envs with few lanes and traffic phases as otherwise there would be too many states). Most cases you will need to use a deep RL algorithm.
