### ISSUE TITLE
How do I run the trained model

### ISSUE THREAD

**Issue by bharath2438** [LucasAlegre/sumo-rl#121]
Hi,
I am trying to understand the single agent q learning model in the examples (ql_4x4grid.py) and I have got the CSVs in the outputs folder. Now, how do I simulate this signal back in sumo-gui so that I can see how the signal works with the newly learnt values?
Thanks in advance.

**Comment by LucasAlegre** [comment]
Hi,

You can do this in the same way as you would do in any other gym / PettingZoo environment. You could for instance copy the ql_4x4grid.py code and remove the learning part, so that the q-values do not change. Saving and loading is not implemented for the tabular QL agent in the repo, but I guess you can simply use pickle to save the agents into a file.

**Comment by bharath2438** [comment]
Thanks for the help, it works now!
