### ISSUE TITLE
Hello, Lucas, I want to find and run your a3c 4*4grid project, but I did not find this project in your experiment. Could you please share this project again? I hope you can answer it as soon as possible, thank you

### ISSUE THREAD

**Issue by dalianmeier** [LucasAlegre/sumo-rl#192]

**Comment by dalianmeier** [comment]
There is a great need to run this event and train and improve on it

**Comment by LucasAlegre** [comment]
You can still find it here: https://github.com/LucasAlegre/sumo-rl/commit/93afeb488f0588800913fd1327ecd5b0c120aeb2#diff-79cdb9539e2198565a8bd6b2398d0bb1c1166cff6d1623f18b9ed693d04f4d38

I removed it since I am no longer maintaining examples using rllib. This is script was not running properly last time I tried, you would need to check rllib documentation and update accordingly.
