### ISSUE TITLE
state\reward design

### ISSUE THREAD

**Issue by Aegis1863** [LucasAlegre/sumo-rl#203]
Thanks for your work again, recently I've tried to introduce some new state design or other reward design, by rewriting or adding new functions in `traffic_signal.py`, and so far, the best case scenario is the default design, which is queue+density and diff-waiting-time, so I'm a little curious, do you have any suggestions for their designs, or can you share your motivation for the default designing

**Comment by LucasAlegre** [comment]
Hi @Aegis1863,

queue + density works well because queue orovides information on number of stopped vehicles, while density complements this information with the number of total vehicles (stopped or moving). We also showed in our paper [Quantifying the Impact of Non-Stationarity in Reinforcement Learning-Based Traffic Signal Control](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=YZnEeJUAAAAJ&citation_for_view=YZnEeJUAAAAJ:2osOgNQ5qMEC) that it helps dealing with non-stationarity.

Regarding the reward function, I don't have that much intuition except that waiting time tends to be more informative than number of queued vehicles because it also related to how long the vehicles are queued. It is also important to be careful and scale the reward function so that it is in a small range (e.g., [-1,1]), which tends to help when using function approximation.

**Comment by Aegis1863** [comment]
@LucasAlegre 
> [Quantifying the Impact of Non-Stationarity in Reinforcement Learning-Based Traffic Signal Control](https://scholar.google.com/citations?

I think this is a very instructive work, especially in the study of non-stationarity. One of the significant differences between traffic environments and other environments is that the former is non-stationary, it's like $s _ {t+1}$ is not only determined by $s_t$ and $a_t$, but also influenced by newly entered vehicles. However, the number of newly entered vehicles is a random variable, which is difficult to learn or observe.

The design of density and queue can indeed eliminate this interference for agent and achieve reinforcement learning control. In my experiment, Rainbow DQN and PPO achieved very good results. In fact, my current attempt is to use model based methods to further reduce trial and error. In the initial attempt, state transitions are relatively easy to learn and there is not much error, but rewards (diff-waiting-time) are difficult to learn. I am making new attempts. Thank you for your contribution.
